version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    restart: always